version: '3.0'
services:
  db:
    image: postgres:14.3
    restart: always
    hostname: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=bancodigital
