ALTER TABLE IF EXISTS proposta ALTER COLUMN cpf SET NOT NULL;
ALTER TABLE IF EXISTS proposta ALTER COLUMN email SET NOT NULL;
ALTER TABLE IF EXISTS proposta ALTER COLUMN cep SET NOT NULL;
ALTER TABLE IF EXISTS proposta ALTER COLUMN logradouro SET NOT NULL;
ALTER TABLE IF EXISTS proposta ALTER COLUMN numero SET NOT NULL;
ALTER TABLE IF EXISTS proposta ALTER COLUMN nome_completo SET NOT NULL;
